title: Interactive badge
hero_image: images/interactive-badge.png
theme: turquoise
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-1, community-0
description: Make a badge that shows your mood
original_url: https://codeclubprojects.org/en-GB/microbit/interactive-badge
interests: wearable-technology
technologies: microbit
site_areas: projects
hardware: microbit
software: ''
version: 3.0.1
last_tested: 2019-03-06
steps: 
- title: Introduction
- title: Displaying an image
- title: Displaying a happy face
- title: 'Challenge: Displaying a sad face'
- title: Creating a simple animation
- title: 'Challenge: Create your own interactive badge!'